[package]
name = "chat"
version = "0.1.0"
authors = ["alexeyakhunov"]

[dependencies]
mio = { git = "https://github.com/carllerche/mio" }
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"